### ISSUE TITLE
SInput hidden

### ISSUE THREAD

**Issue by jprograming** [placetopay-org/spartan-vue#123]
Cuando se renderiza un input de tipo hidden se muestra una línea gris.

![Captura desde 2024-04-03 22-20-11](https://github.com/placetopay-org/spartan-vue/assets/3971099/84dc25af-239e-46ff-b9af-efb9dc9c14f7)

**Comment by JuanZea** [comment]
Solucionado en [beta.82](https://www.npmjs.com/package/@placetopay/spartan-vue/v/2.0.0-beta.82)
