### ISSUE TITLE
Poder ocultar value de SSelectGroup

### ISSUE THREAD

**Issue by mascam97** [placetopay-org/spartan-vue#95]
El select group, es un  tipo de select que puede agrupar opciones
<img width="252" alt="image" src="https://github.com/placetopay-org/spartan-vue/assets/44913087/a1f36e23-5a53-4330-9597-adc438f746b5">

Este por defecto para las opciones muestra tanto el value como el label, sin embargo cuando el value es bastante largo, o cuando el value es el mismo valor que label, no se ve bien que value se vea. Así como un select normal, que no muestra el value se vería mejor.

Por lo que se sugiere que mediante de una propiedad se pueda configurar que se muestre el value o no se muestre.

**Comment by JuanZea** [comment]
El caso de uso esta cubierto por el componente SCombobox que cuenta con un slot para personalizar el contenido de la opción
